# _____________                   _______________         
# ___    |__  /_____ ________________(_)_  /__  /_____  __
# __  /| |_  /_  __ `/  ___/_  ___/_  /_  __/  __/_  / / /
# _  ___ |  / / /_/ // /__ _  /   _  / / /_ / /_ _  /_/ / 
# /_/  |_/_/  \__,_/ \___/ /_/    /_/  \__/ \__/ _\__, /  
#                                                /____/   

import = [
"~/Documents/Colorschemes/Alacritty/paradise.toml"
]

[font]
normal = { family = "tewi", style = "regular" }
bold = { family = "tewi", style = "bold" }
italic = { family = "tewi", style = "regular" }
bold_italic = { family = "tewi", style = "bold" }
size=8

[window]
padding = { x = 25, y = 25}
# opacity = 0.75
